'use client';

import React, { useState } from 'react';
import { analyzeInjury } from '@/lib/api';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import styles from './InjuryAnalyzer.module.css';

const InjuryAnalyzer: React.FC = () => {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setPreview(URL.createObjectURL(selectedFile));
      setAnalysis(null);
      setError(null);
    }
  };

  const handleAnalyze = async () => {
    if (!file) return;

    setLoading(true);
    setError(null);
    
    try {
      // Get token from localStorage
      const token = localStorage.getItem('access_token') || '';
      const result = await analyzeInjury(file, token);
      setAnalysis(result.analysis);
    } catch (err: any) {
      setError(err.message || 'Something went wrong during analysis.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2>Injury Context Analysis</h2>
        <p>Upload an image of the injured part for AI-powered assessment</p>
      </div>

      <div className={styles.uploadSection}>
        <label className={styles.dropZone}>
          <input 
            type="file" 
            accept="image/*" 
            onChange={handleFileChange} 
            className={styles.hiddenInput} 
          />
          {preview ? (
            <img src={preview} alt="Preview" className={styles.previewImage} />
          ) : (
            <div className={styles.placeholder}>
              <span className={styles.icon}>📷</span>
              <span>Click to upload or drag & drop</span>
            </div>
          )}
        </label>

        {file && (
          <button 
            onClick={handleAnalyze} 
            disabled={loading}
            className={styles.analyzeButton}
          >
            {loading ? 'Analyzing...' : 'Analyze Injury'}
          </button>
        )}
      </div>

      {error && <div className={styles.error}>{error}</div>}

      {analysis && (
        <div className={styles.resultCard}>
          <h3>Analysis Result</h3>
          <div className={styles.analysisText}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {analysis}
            </ReactMarkdown>
          </div>
          <div className={styles.disclaimer}>
             ⚠️ This analysis is generated by AI and is for informational purposes only. Consult a doctor for medical emergencies.
          </div>
        </div>
      )}
    </div>
  );
};

export default InjuryAnalyzer;
